SystemVerilog: several kind related fixes
universal-ctags/ctags pull request #2684
Opened 2020-10-31 06:00 UTC by hirooih

- bug fix of block-end handling
- add support of checker-block, sequence-block, and clocking-block
- add tests for fixes above

It seems I made a mistake.  I update my master and rebase this branch with the master.
"Commits on Oct 27, 2020" below are updates already merged on #2680.

2020-10-31 06:08 UTC, hirooih commented
> It seems I made a mistake. I update my master and rebase this branch with the master.
> "Commits on Oct 27, 2020" below are updates already merged on #2680.

"Merge remote-tracking branch 'upstream/master' 5d5f60b" and above are already merged on #2680.
I have to read the Branch chapter of Git manual, again...

2020-10-31 08:47 UTC, hirooih commented
Uncovered lines in the first pull-request showed me a bug.  I've push the fix.

2020-10-31 12:27 UTC, masatake commented
> "Merge remote-tracking branch 'upstream/master' 5d5f60b" and above are already merged on #2680.
I have to read the Branch chapter of Git manual, again...

I assume your master branch at local system is clean. I also assume you set "upstream" in your .git/config correctly.

```
$ git checkout master
$ git pull upstream master:master
$ git checkout sv-kind-fixes
$ git rebase master
$ git push --force origin sv-kind-fixes:sv-kind-fixes
```

2020-10-31 12:33 UTC, masatake commented
If you made your master branch broken at local system, you can fix with:
```
git checkout sv-kind-fixes
git branch -D master
git fetch upstream
git checkout upstream/master
git checkout -b master
```
Now your master branch at your local system becomes "clean".
"upstream" is defined in my .git/config as:
```
[remote "upstream"]
#       url = https://github.com/fishman/ctags.git
        url = git@github.com:fishman/ctags.git
        fetch = +refs/heads/*:refs/remotes/upstream/*
```

2020-10-31 15:23 UTC, hirooih commented
@masatake san,

Thank you for your advise.

```
$ git remote -v
origin  https://github.com/hirooih/ctags.git (fetch)
origin  https://github.com/hirooih/ctags.git (push)
upstream        https://github.com/universal-ctags/ctags.git (fetch)
upstream        https://github.com/universal-ctags/ctags.git (push)
```
.git/config

```
$ grep 'remote "upstream"' -A2 .git/config
[remote "upstream"]
        url = https://github.com/universal-ctags/ctags.git
        fetch = +refs/heads/*:refs/remotes/upstream/*
```

I did the following steps.

```
# make the master branch up-to-date
git checkout master
git fetch upstream
git merge upstream/master
# rebase sv-kind-fixes on master
git checkout sv-kind-fixes
git rebase master
# push to origin
git push
```

I am referring [Pro Git Book , chapter "3. Git Branching"](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell). 
I don't understand what is wrong.

Should I do `git push` after `git merge upstream/master`?

Before the 2nd pull-request I did

```
# make master up-to-date
git checkout master
git push --force
git checkout sv-kind-fixes
git push --force
```

But it seems that it did not work.
Should I remove the master branch as you wrote?

2020-10-31 20:28 UTC, masatake commented
> Should I do git push after git merge upstream/master?

Don't afirad of removing "master" locally as far as it is clean.

You should not merge upstream/master to master in my understanding.
Instead, you should "pull". If pulling is failed, your local "master" is dirty.
In such case, you should delete (after making a backup if you want) the dirty "master" branch, you
should make clean one.

NOTE: git is so flexible. So what I write here is not the only way to keep things good.

Do you have any important commits in your local master branch?
You should not have them. I called the master branch, including commits that are not merged to the upstream yet, "dirty."
The master branch at your local system must be clean.
A clean master branch doen't include any commits that are not merged to the upstream yet.
Such a clean master branch, Youn can do "git pull upstream master:master" without a trouble.

Steps for making clean local "master":
1. making a backup if you want: "git checkout master; git checkout -b backup"
2. get latest branches from upstream: "git fetch upstream"
3. making a clean "master" locally: "git checkout upstream/master; git checkout -b master."
now the master becomes clean.

How to update the local "master":
"git checkout master; git pull upstream master:master"

How to rebase your local sv-kind-fixes on the new "master":
1. rename CURRENT sv-kind-fixes to sv-kind-fixes-backup: "git checkout sv-kind-fixes; git branch -m sv-kind-fixes-backup".
2. make new sv-kind-fixes: "git checkout master; git checkout -b sv-kind-fixes"
3. cherry-pick the commits in sv-kind-fixes-backup: 
   3.1 See the output of "git log sv-kind-fixes-backup", and memorize the commits you want to cherry-pick.
   3.2 Do cherry-pick: "git checkout sv-kind-fixes; git cherry-pick commit0; git cherry-picks commit1;..."

There are  3 "master" branches:
1 "master" at upstream
2. "master" at your GitHub site
3. "master" at local

2. is not important. See mine, https://github.com/masatake/ctags/ . I don't update it.

What you can do for "master" at local is only "git checkout master; git pull upstream master:master".
What you can do for "master" at upstream is only pressing the "merge" button at GtiHub web page.

The data flow is one directional.
```
your topic branch1 -[push]-> your topic branch at your GitHub site -[pressing "merge" button]->"master" at upstream 
-[pull]-> "master" at local -[git checkout -b]-> your topic branch2 -...
```

I frequetly making a topic branch. I commits changes to local "master". As the result, the "master" branch becomes dirty.
In such a case, I will do: "git checkout master; git branch -m TOPIC; git checkout upstream/master; git checkout -b master".

If a topic branch becomes older, you want to rebase on master: "git checkout master; git pull upstream master:master; git checkout TOPIC; git rebase master".

If you cannot rid your trouble, please send a mail to yamato@redhat.com in Japanese.

2020-11-07 19:52 UTC, masatake commented
@hirooih, I found I received your mail. The mail was put to "spam". I'm sorry. I have just replied.
I'm writing this here because I'm afraid my reply mail goes to your "spam" folder :-P

2020-11-08 04:03 UTC, hirooih commented
@masatake san
Thank you. I've replied again.

> I'm writing this here because I'm afraid my reply mail goes to your "spam" folder :-P

Me, too.

2020-11-08 14:30 UTC, hirooih commented
@masatake san

As you wrote first, my master branch was broken.  By following your advice I could push the branch cleanly.
Please review it.

Thank you.

```
# delete master branch
git checkout sv-kind-fixes
git branch -D master
git fetch upstream
git checkout upstream/master
git checkout -b master

# create a new branch
git fetch upstream
git checkout -b sv-kind-fixes-new upstream/master

# cherry-pick the commits in-kind-fixes
git cherry-pick 53a86480
git cherry-pick d3a8d3f9
git cherry-pick 653d24d7
git cherry-pick 15ad93ab
git cherry-pick df6a53df
git cherry-pick 85e24098
git cherry-pick 2a90d1b4
git cherry-pick 06908970
git cherry-pick b2e27ae4
git cherry-pick a494b897

# rename sv-kind-fixes to sv-kind-fixes-corrupted
git checkout sv-kind-fixes
git branch -m sv-kind-fixes-corrupted

# rename sv-kind-fixes-new to sv-kind-fixes
git checkout sv-kind-fixes-new
git branch -m sv-kind-fixes

# push fixed sv-kind-fixes
git push origin --force sv-kind-fixes
```

2020-11-09 17:22 UTC, masatake commented on parsers/verilog.c
>  			processBegin(token);
How about renaming `processBegin` to `processBlock`? Just an idea.

2020-11-09 18:20 UTC, masatake commented
When thinking about what I have ever done, I cannot say much but...

I cannot parse some commits.

```
commit 5b74f74950d57eca66784d67d41c332f1594ec8c
Author: Hiroo HAYASHI <24754036+hirooih@users.noreply.github.com>
Date:   Fri Oct 30 22:52:53 2020 +0900

    Units,SystemVerilog: update for assertion fixes:
    systeverilog-github2635.d

```

The first line of commit log ends with `:`. So I cannot parse well.
I use "foo:" freqeuetnly in commit log and documents when talking about a field "foo:".
In that case, I wrap the name of field with double quotes. However, there is no field "fixes:" in ctags.


I guess "Units,SystemVerilog: update systeverilog-github2635.d for the fixes about assertion" or
"
```
Units,SystemVerilog: update for assertion

Fixes: systeverilog-github2635.d
```
".

```
commit c13db5991cd171c71bf9f681cfb18b9b3e1cfa6b
Author: Hiroo HAYASHI <24754036+hirooih@users.noreply.github.com>
Date:   Fri Oct 30 23:37:19 2020 +0900

    SystemVerilog: add checker, clocking, and sequence kinds. Add restrict on K_ASSERTION
    
    bug fix: processAssertion() clears block name not to be reused
    clocking is not implemented yet
```

The first line includes '.'. I'm not comfortable about it. The sentence after "bug fix:" is not ended with '.'.
If it was me, I will separate the commit into two commits to make writing the commit log easier:
```
SystemVerilog: add checker, clocking, and sequence kinds
SystemVerilog: add "restrict" on K_ASSERTION
```
.
However, you may don't want to do "git rebase" again for splitting the commit.

Another better approach that I cannot do well because of my limitted English skill is:

```
SystemVerilog: fix processAssertion() clearing block names not to be reused

* add checker, clocking, and sequence kinds.
* add restrict on K_ASSERTION.

NOTE: clocking is not implemented yet.
```
.

I don't say about the details.

2020-11-09 18:43 UTC, masatake commented
This is optional comments. 

Your pull request consists of commits like:
```
* code change0
* code change1
* modify test cases for the changes AND add test cases
```

This implies "make units" may fail when I checked out code charnge0 or code change1, a commit in the middle of the pull request.
I want you to avoid this style if possible.  Because this makes git bisect hard. I would like to make any commit in the master
branch "make units" safe.

That means ideal commits in a pull request should be:
```
* code change0 and modification of test cases for code change0
* code change1 and modification of test cases for code change1
* add test cases
```

This is not only for "make units" safe. In many case, reviewing the commits easier.
By reading one commit, from the part of "test cases for code changeN" the commit, a reviewer can know the impact
of "code change0".  The reviewer doesn't need to read more than two commits at once for reviewing.

In addition, the ideal commits allows partial merging.
```
* code change0
* code change1
* modify test cases for the changes AND add test cases
```
In this style, we can merge all the commits or nothing. 
Consider the situation: code change0 looks good. However, code chage0 doesn't. 
In such a case, I would like to merge the code change0, especially when the code change0 fixes a critical bug.
However, I cannot because when "code change0" is merged, "make units" may report failure.

```
* code change0 and modification of test cases for code change0
* code change1 and modification of test cases for code change1
* add test cases
```

On the other hand, we can merge
"* code change0 and modification of test cases for code change0" separately though "* add test cases" is
needed for comprehensive testing for "code change0". 

I found a good phrase representing what I want: "cherry-pick portable."

2020-11-09 18:44 UTC, masatake requested changes
Please, update the commit logs.

2020-11-09 23:33 UTC, hirooih commented
@masatake san,
Thank you for your valuable comments.  I will work on them.

2020-11-10 14:56 UTC, hirooih commented
@masatake san

Let me confirm before starting updates.

> * code change0
> * code change1
> * modify test cases for the changes AND add test cases

I used this style to follow [this rule](https://docs.ctags.io/en/latest/development-process.html#rules-for-modifying-our-repository).
I thought I had to separate parser C code changes from unit test changes.

The prefix of a commit log should be;

* SystemVerilog: verilog.c change0 only
* SystemVerilog,Units: verilog.c change1 and test case change for the change1
* Units,SystemVerilog: test case (under Units/parser-verilog.r/) change2 only

Am I correct?

***

> However, you may don't want to do "git rebase" again for splitting the commit.

I found the section "Splitting a Commit" in [Git Pro](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History).  I want to learn and try this.

2020-11-10 16:00 UTC, masatake commented
> I used this style to follow this rule.

I'm sorry if I wrote are inconsistent.

> The prefix of a commit log should be;
> 
>     SystemVerilog: verilog.c change0 only
>     SystemVerilog,Units: verilog.c change1 and test case change for the change1
>     Units,SystemVerilog: test case (under Units/parser-verilog.r/) change2 only
> 
> Am I correct?

The rules for prefix are not so strict.

>     SystemVerilog,Units: verilog.c change1 and test case change for the change1

This is o.k. You can remove ",Units". If you want to emphasize the change for Units, append ",Units" to the prefix.

> Units,SystemVerilog: test case (under Units/parser-verilog.r/) change2 only

For this I use: "Units: test case (under Units/parser-verilog.r/) change2 only"
"SystemVerilog" in prefix implies changing the code for SystemVerilog.

If you want to represent that the change is about test cases for SystemVerilog, you can use
"Units(SystemVerilog):". I use this form in "docs(web)", "docs(man)", and "docs(web,man)".

Again, thie rules I wrote here are not so strictly applied.

2020-11-10 23:26 UTC, hirooih commented
I understand.  Thank you.

2020-11-11 13:31 UTC, hirooih commented
@masatake san,

I've committed the fix.
I like this style; "commit a fix with test for it".

> However, you may don't want to do "git rebase" again for splitting the commit.

I decided not to split the commit on this case because I thought it was not worth to be splitted.

2020-11-11 20:06 UTC, masatake approved these changes
Looks good for me. Please, merge this. Thank you.

2020-11-11 23:27 UTC, hirooih commented
Thank you.

2020-11-11 23:51 UTC, k-takata commented
Oh? You closed this without merging?

2020-11-12 00:43 UTC, merged

2020-11-12 00:44 UTC, hirooih commented
> Oh? You closed this without merging?

Thanks!
# I did the same mistake, before...