SystemVerilog: fix for processDesignElementL() not to go into infinite-loop (fix for #2738)
universal-ctags/ctags pull request #2744
Opened 2020-11-29 14:37 UTC by hirooih

Fix for #2738.

I reviewed all loop and refactored some of them.

2020-11-29 14:53 UTC, masatake requested changes

2020-11-29 14:53 UTC, masatake commented on Units/parser-verilog.r/systemverilog-illegal.d/input.sv
> +interface static 0
It is better to introduce a new file for the broken input.
How do you think about putting these 3 lines into a new file, `input-0.sv`?
The "make units" processes "input.sv" and "input-[0-9].sv".

2020-11-29 14:58 UTC, hirooih commented on Units/parser-verilog.r/systemverilog-illegal.d/input.sv
> +interface static 0
> The "make units" processes "input.sv" and "input-[0-9].sv".

I did not know this.
Do we require input.sv?  In other words,  input-0.sv (for original) and input-1.sv (for new one) are OK?

2020-11-29 15:01 UTC, masatake commented on Units/parser-verilog.r/systemverilog-illegal.d/input.sv
> +interface static 0
Yes, we require input.sv for the original file.
See also
https://docs.ctags.io/en/latest/units.html#how-to-write-a-test-case
.

2020-11-29 15:10 UTC, hirooih commented on Units/parser-verilog.r/systemverilog-illegal.d/input.sv
> +interface static 0
It works.  I've pushed again.

2020-11-29 15:15 UTC, masatake commented on Units/parser-verilog.r/systemverilog-illegal.d/input.sv
> +interface static 0
If you don't treat input.sv special, you can make input.sv empty like https://github.com/universal-ctags/ctags/pull/2740/files .

2020-11-29 15:25 UTC, hirooih commented on Units/parser-verilog.r/systemverilog-illegal.d/input.sv
> +interface static 0
> Units/TEST/input[-_][0-9].* Units/TEST/input[-_][0-9][-_]*.* optional

I made input.sv as an empty file.  And rename input-[01].sv as;
input-0-2724.sv
input-1-2738.sv

2020-11-29 15:26 UTC, hirooih commented on Units/parser-verilog.r/systemverilog-illegal.d/input.sv
> +interface static 0
> If you don't treat input.sv special, you can make input.sv empty like https://github.com/universal-ctags/ctags/pull/2740/files .

Sorry, I read this after I pushed again.

2020-11-29 15:40 UTC, hirooih commented
Uncovered lines are sanity checks for unexpected inputs.  They should be OK.

I am thinking that I will use systemverilog-illegal.d/input.sv to cover these uncovered lines.

2020-11-30 03:49 UTC, masatake approved these changes

2020-11-30 09:27 UTC, merged