Parse member variables using templates with forward declared types
universal-ctags/ctags pull request #2869
Opened 2021-02-15 19:17 UTC by drichardson

Fixes  #2867.

2021-02-16 01:05 UTC, masatake commented
Thank you. Could you squash the changes into one commit?
In addition, I would like you to use `C++: ...` as the prefix for the commit log.

2021-02-16 02:24 UTC, drichardson commented
> 
> 
> Thank you. Could you squash the changes into one commit?
> In addition, I would like you to use `C++: ...` as the prefix for the commit log.

Done and done.

2021-02-16 02:39 UTC, masatake commented
Thank you.
Let's wait for the maintainer to find the time for review:-)

2021-04-01 17:07 UTC, masatake requested changes

2021-04-01 17:07 UTC, masatake commented
@pragmaware, could you look at this one?

2021-04-01 17:09 UTC, masatake commented
@drichardson, sorry for being late.
I would like you to change the local variable. Could you fix it and push --force again?
If we cannot get a comment from the parser maintainer, I will merge this.

2021-04-01 17:47 UTC, drichardson commented on parsers/cxx/cxx_parser_block.c
> +	int in_triangle = 0;
Done

2021-04-01 17:49 UTC, drichardson commented
> I would like you to change the local variable. Could you fix it and push --force again?
Done.

2021-04-01 18:11 UTC, masatake approved these changes

2021-04-01 18:11 UTC, masatake commented
Thank you.

2021-04-18 20:10 UTC, drichardson commented
Time to merge?

2021-04-19 22:11 UTC, masatake commented
I will merge this.
@pragmaware, please look at this when you find a time.

2021-04-19 22:11 UTC, merged

2021-04-19 22:12 UTC, masatake commented
@drichardson, thank you for the contribution.