Units, docs(web): add cases for testing direction flags of langdef option
universal-ctags/ctags pull request #3143
Opened 2021-09-01 19:52 UTC by masatake

Surprisingly I didn't write the test cases for them.
The new test cases are based on https://docs.ctags.io/en/latest/running-multi-parsers.html#direction-flags.

More surprisingly the code works as written in the document:-)

2021-09-01 20:02 UTC, masatake commented
@hirooih, I wrote test cases based on the document you reviewed.
The cases are simple enough so they will help readers understand the documents.

2021-09-02 13:35 UTC, hirooih requested changes
Units tests are OK.

At least add a "more".

2021-09-02 14:47 UTC, masatake commented on docs/running-multi-parsers.rst
>  See ":ref:`optlib_directions`" in ":ref:`optlib`" for examples of using the
I agree with you. I will update the document again.

2021-09-03 17:48 UTC, masatake commented on docs/running-multi-parsers.rst
>  See ":ref:`optlib_directions`" in ":ref:`optlib`" for examples of using the
I didn't remember the examples were in optlib.rst. Thank you for pointing out this.
So I withdraw the change for docs/running-multi-parsers.rst.

I will just introduce "TESTCASE:" flag.

2021-09-04 03:55 UTC, hirooih approved these changes
I see.  This is another good selection.

2021-09-04 05:29 UTC, merged