Verilog typeref field
universal-ctags/ctags pull request #3471
Opened 2022-08-26 18:11 UTC by masatake

Verilog: fill typeref fields of instances
    
This one is partially based on
https://github.com/universal-ctags/ctags/compare/master...my2817:ctags:master
reported and written by @my2817 at #3469.
    
Capturing the module names of instances is also proposed in #3469.
However, it is not in the scope of this commit.

2022-08-27 13:09 UTC, hirooih requested changes
Thank you for your PR.
It was much more easy than I thought to add typeref.  Thanks for your clean design.

I put some comments.

2022-08-27 13:09 UTC, hirooih commented on parsers/verilog.c
> +	tokenInfo *module = dupToken(token); // Not a definition. Referencing a module
This function is not only for a module-instantiation.
So the variable name `module` is not proper.

I am always trying to narrow a scope of variable as narrow as possible.  How about the following fix?

```diff
diff --git a/parsers/verilog.c b/parsers/verilog.c
index 73cc70da4..49ed9e52a 100644
--- a/parsers/verilog.c
+++ b/parsers/verilog.c
@@ -1835,21 +1835,19 @@ static int tagIdsInPort (tokenInfo *const token, int c, verilogKind kind, bool m
 // Tag a list of identifiers in a data declaration
 static int tagIdsInDataDecl (tokenInfo* token, int c, verilogKind kind)
 {
-       tokenInfo *module = dupToken(token); // Not a definition. Referencing a module
-       module->kind = K_MODULE;                         // for defining an instance.
-
        c = skipClassType (token, c);
        if (c == ';')
-               goto out;
+               return c;
 
        // skip drive|charge strength or type_reference, dimensions, and delay for net
        if (c == '(')
                c = skipPastMatch ("()");
        c = skipDimension (c);
        if (c == '.')
-               goto out;       // foo[...].bar = ..;
+               return c;       // foo[...].bar = ..;
        c = skipDelay (token, c);       // ## (cycle delay)
 
+       tokenInfo *token_saved = dupToken(token); // maybe a module_identifier
        while (c != EOF)
        {
                bool with = false;
@@ -1863,7 +1861,7 @@ static int tagIdsInDataDecl (tokenInfo* token, int c, verilogKind kind)
                        if (c == '=')
                                c = skipExpression (c);
                }
-               else if (c == '(' || c == '[')  // should be instance
+               else if (c == '(' || c == '[')  // should be an instance
                {
                        c = skipDimension (c); // name_of_instance {unpacked_dimension}
                        c = skipPastMatch ("()"); // list_of_port_connections
@@ -1872,8 +1870,9 @@ static int tagIdsInDataDecl (tokenInfo* token, int c, verilogKind kind)
                        // var `add_t(foo) = '0;
                        if (c == ';' || c == ',')
                        {
+                               token_saved->kind = K_MODULE;   // for type_ref field
                                verbose ("find instance: %s with kind %s\n", vStringValue (token->name), getNameForKind (K_I
NSTANCE));
-                               createTagFull (token, K_INSTANCE, module);
+                               createTagFull (token, K_INSTANCE, token_saved);
                        }
                }
                c = skipMacro (c, token);       // `ifdef, `else, `endif, etc. (before comma)
@@ -1882,8 +1881,7 @@ static int tagIdsInDataDecl (tokenInfo* token, int c, verilogKind kind)
                c = skipWhite (vGetc ());       // skip ','
                c = skipMacro (c, token);       // `ifdef, `else, `endif, etc. (after comma)
        }
- out:
-       deleteToken (module);
+       deleteToken (token_saved);
        return c;
 }
```

2022-08-27 13:09 UTC, hirooih commented on parsers/verilog.c
> +
Good idea.

2022-08-27 14:58 UTC, masatake commented on parsers/verilog.c
> +
You can find many samples in the output of 
```
$ git log --grep=typeref
```
4549fa5665935a902796567941d921f132de4518 looks not so complicated.

2022-08-28 02:06 UTC, hirooih approved these changes
Thank you for your clean fixes as always.

2022-08-28 02:06 UTC, hirooih commented on parsers/verilog.c
> +			createTagWithTypeRef (content, content->kind, NULL);
I overlooked this yesterday.
First I thought we should add prototype definition of `createTag()` and use `createTag()` as is here.

But after reading the source code, now I agree with your decision.  Using `createTagWithTypeRef()` is better for readability.

2022-08-28 02:06 UTC, hirooih commented on parsers/verilog.c
> +
> `git log --grep=...`

This is a really useful tip.  Thanks you.

2022-08-28 06:38 UTC, merged