docs(man): write about guest parsers
universal-ctags/ctags pull request #3892
Opened 2023-12-22 20:21 UTC by masatake

Close #3888
Close #3007

2023-12-23 02:29 UTC, hirooih requested changes
It is very clearly written in general.
I commented on the questions I had when I read it.

A typo should be fixed.

Others are comments.

2023-12-23 18:51 UTC, masatake commented on docs/man/ctags-client-tools.7.rst
> +between a kind single-letter and a kind long-name.
How about "a single-letter for a kind and a long-name for the kind" ?

2023-12-23 18:51 UTC, masatake commented on docs/man/ctags-client-tools.7.rst
> +From the seoncd field of the output, a tool can know the mapping
Thank you.

2023-12-23 19:05 UTC, masatake commented on docs/man/ctags-client-tools.7.rst
> +``--fields=+K`` may be helpful.
Thank you.

Surprisingly (and sadly), many client tools hardcode single-letter kinds and long-name kinds. Such a tool can say what is ``c`` in JavaScript input. The tool also knows the language for `*.js` file. I'll revise the sentences you pointed out.

2023-12-23 19:16 UTC, masatake commented on docs/man/ctags-client-tools.7.rst
> +parse tags output:
I will remove the description about ``--fields=+z``.

2023-12-24 00:23 UTC, hirooih commented on docs/man/ctags-client-tools.7.rst
> +between a kind single-letter and a kind long-name.
It is better than mine.

2023-12-24 23:44 UTC, hirooih approved these changes

2023-12-24 23:46 UTC, hirooih commented
I could read very smoothly.
Thanks.

2023-12-25 02:41 UTC, merged

2023-12-25 02:41 UTC, masatake commented
@hirooih Thank you.